name: Get New Package Version
description: Sets the version as ENV variable.

inputs:
  CHANNEL:
    required: true
    description: 'The channel to get the version to (ga, cloud, beta).'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
            CLEAN_PACKAGE_VERSION=$(node -p "require('./package.json').version")

            # The condition must be changed before we create the new hostintg release
            if [[ ${{ inputs.CHANNEL }} != "cloud" ]]; then
                PACKAGE_VERSION=${CLEAN_PACKAGE_VERSION}-${{ inputs.CHANNEL }}-rc
            else
                PACKAGE_VERSION=${CLEAN_PACKAGE_VERSION}-${{ inputs.CHANNEL }}
            fi

            echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
            echo "CLEAN_PACKAGE_VERSION=${CLEAN_PACKAGE_VERSION}" >> $GITHUB_ENV

